name: My-GitHub-Action-Basic

on:
  push: 
    branches: [ main ]

jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start test
        run: echo Start testing!
      
  build:
    runs-on: ubuntu-latestxxx

    needs: [my_test]
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Print Hello message
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
